//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Baze2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KladionicaModelContainer : DbContext
    {
        public KladionicaModelContainer()
            : base("name=KladionicaModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Dogadjaj> Dogadjajs { get; set; }
        public virtual DbSet<Tiket> Tikets { get; set; }
        public virtual DbSet<Korisnik> Korisniks { get; set; }
        public virtual DbSet<Radnik> Radniks { get; set; }
        public virtual DbSet<Lokal> Lokals { get; set; }
        public virtual DbSet<Pice> Pices { get; set; }
    }
}
